### ISSUE TITLE
Typo (unisson)

### ISSUE THREAD

**Issue by hsyl20** [vgay/vgay.github.io#1]
There is a typo in Armando's Rhumba:

https://github.com/vgay/vgay.github.io/blob/2f24eaa5c7363b52584aff1f089e8c36e782cc52/media/files/partitions/Armando'sRhumba.ly#L126

It should be "unison"

**Comment by jeanas** [comment]
Um, those scores are annotated in French, not in English.

**Comment by hsyl20** [comment]
Ahah sorry, I missed that :)
